app/faculty/models.py
from app import db


class Faculty(db.Model):
    __tablename__ = "faculty"

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(50), nullable = False, unique = True)
    code = db.Column(db.String(10), nullable=False, unique = True)



    def __repr__(self):
        return f"<Faculty>{self.name}"

app/faculty/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, HiddenField
from wtforms.validators import *

class FacultyForm(FlaskForm):
    id = HiddenField("id")
    name=StringField("Faculty Name: ", validators=[DataRequired()])
    code=StringField("Faculty Code: ", validators=[DataRequired()])
    submit=SubmitField("Save Changes")

    

app/faculty/__init__.py
from flask import Blueprint


faculty_bp=Blueprint('faculty',__name__, template_folder="templates", static_folder= 'statics')

from app.faculty import views

app/faculty/views.py
from flask import *
from app.faculty import faculty_bp
from app.faculty.forms import FacultyForm
from app.faculty.models import Faculty
from app import db

@faculty_bp.route("/faculty_list", methods=["GET"])
def get_faculty_list():
    faculty=Faculty.query.all()
    return render_template("list_faculty.html", fac=faculty)


@faculty_bp.route("/add_faculty", methods=["GET", "POST"])
def add_faculty():
    forms=FacultyForm()
    if forms.validate_on_submit():
        faculty_name=forms.name.data
        faculty_code=forms.code.data

        new_faculty=Faculty(name=faculty_name, code=faculty_code)
        db.session.add(new_faculty)
        db.session.commit()

        return redirect(url_for("faculty.get_faculty_list"))
    return render_template("add_faculty.html", form=forms)


    

@faculty_bp.route('/delete_faculty/<int:id>', methods=['POST'])
def delete_faculty(id):
    faculty=Faculty.query.get_or_404(id)
    db.session.delete(faculty)
    db.session.commit()
    return redirect(url_for('faculty.get_faculty_list'))



@faculty_bp.route('/edit_faculty/<int:id>', methods=['GET', 'POST'])
def update_faculty(id):
    faculty=Faculty.query.get_or_404(id)
    form=FacultyForm(obj=faculty)
    if form.validate_on_submit():
        form.populate_obj(faculty)
        db.session.commit()
        return redirect(url_for('faculty.get_faculty_list'))
    
    return render_template('add_faculty.html', form=form)


@faculty_bp.route('/delete_all_faculty/', methods=['POST'])
def delete_all_faculty():
    Faculty.query.delete()
    db.session.commit()
    return redirect(url_for('faculty.get_faculty_list'))

app/faculty/templates/add_faculty.html
{% extends 'index.html' %} {% block title %} Add Faculty {% endblock %} {% block
content %}

<form method="POST">
  <div class="centered-group">
    <p>{{form.hidden_tag()}}</p>

    <p>{{form.name.label()}} {{form.name()}}</p>

    <p>{{form.code.label()}} {{form.code()}}</p>
    <p>{{form.submit(class="button_primary")}}</p>

  </div>
</form>

{% endblock %}

app/faculty/templates/list_faculty.html
{% extends "index.html" %}

{% block title %} Faculty List {% endblock %}

{% block content %}

<br>
<div class="table">
    <a class= "button_primary" href="{{url_for('faculty.add_faculty')}}">Add Faculty</a> &nbsp
    <span style="margin-right: 20px;"></span> 
    <form methods="POST" style="display: inline;" action="{{url_for('faculty.delete_all_faculty')}}"> 
        <button type="submit" onclick="return confirm('You sure you wan delete all faculties')" class="button_danger">Delete all Faculties</button>
    </form>



</div>
</br>



<table class="table">
    <tr>
        <th>S/N</th>
        <th>Faculty Name</th>
        <th>Faculty Code</th>
        <th>Action</th>
    
    </tr>
{% for i in fac %}
    <tr>
        <td>{{ i.id }}</td>
        <td>{{ i.name }}</td>
        <td>{{ i.code }}</td>
        <td><a class= "button_primary" href="{{url_for('faculty.update_faculty', id=i.id)}}">Edit</a> &nbsp
        <form style="display: inline;" action="{{url_for('faculty.delete_faculty', id=i.id)}}" method="POST">
            <button type="submit" onclick="return confirm('You sure you want delete this row')" class="button_danger">Delete</button>
        </form></td> 
    
    </tr>

    {% endfor %}
</table>


{% endblock %} 