app/department/models.py
from app import db


class Department(db.Model):
    __tablename__ = "department"

    id = db.Column(db.Integer, primary_key = True)
    faculty_id = db.Column(db.Integer, db.ForeignKey("faculty.id"), nullable = False)
    name = db.Column(db.String(50), nullable = False, unique = True)
    code = db.Column(db.String(10), nullable=False, unique = True)
    #desc = db.Column(db.String(10), nullable=False, unique = True)

    faculty = db.relationship("Faculty", backref="department")

    def __repr__(self):
        return f"<Department>{self.name}"

app/department/forms.py
from flask_wtf import *
from wtforms import *
from wtforms.validators import *
from app.faculty.models import Faculty

class DepartmentForm(FlaskForm):
    id = HiddenField("id")
    faculty_id=SelectField("Select Faculty")
    name=StringField("Department Name: ", validators=[data_required()])
    code=StringField("Department Code: ", validators=[data_required()])
    submit=SubmitField("Save Changes")

    def __init__(self, *args, **kwargs):
        super(DepartmentForm, self).__init__(*args, **kwargs)
        self.faculty_id.choices=[(faculty.id, faculty.name) for faculty in Faculty.query.all()]

    

app/department/__init__.py
from flask import Blueprint

department_bp=Blueprint('department',__name__, template_folder="templates", static_folder= 'statics')

from app.department import views

app/department/views.py
from flask import *
from app.department import department_bp
from app.department.models import Department
from app.department.forms import DepartmentForm
from app import db

@department_bp.route("/department_list", methods=["GET"])
def get_department_list():
    department=Department.query.all()
    return render_template("list_department.html", dep=department)


@department_bp.route("/add_department", methods=["GET", "POST"])
def add_department():
    forms=DepartmentForm()
    if forms.validate_on_submit():
        faculty_id = forms.faculty_id.data
        department_name = forms.name.data
        department_code = forms.code.data

        new_department = Department(faculty_id=faculty_id, name = department_name, code = department_code)
        db.session.add(new_department)
        db.session.commit()
        return redirect(url_for("department.get_department_list"))

    return render_template("add_department.html", form=forms)


@department_bp.route('/delete_department/<int:id>', methods=['POST'])
def delete_department(id):
    department=Department.query.get_or_404(id)
    db.session.delete(department)
    db.session.commit()
    return redirect(url_for('department.get_department_list'))


@department_bp.route("/update_department/<int:id>", methods=["GET", "POST"])
def update_department(id):
    department=Department.query.get_or_404(id)
    form=DepartmentForm(obj=department)
    if form.validate_on_submit():
        form.populate_obj(department)
        db.session.commit()
        return redirect(url_for("department.get_department_list"))
    
    return render_template("add_department.html", form=form)



@department_bp.route('/delete_all_department/', methods=['POST'])
def delete_all_department():
    Department.query.delete()
    db.session.commit()
    return redirect(url_for('department.get_department_list'))

app/department/templates/add_department.html
{% extends 'index.html' %} {% block title %} Add Department {% endblock %} {%
block content %}

<form method="POST">
  <div class="centered-group">
    <p>{{form.hidden_tag()}}</p>

    <p>{{form.faculty_id.label()}} {{form.faculty_id()}}</p>

    <p>{{form.name.label()}} {{form.name()}}</p>
    <p>{{form.code.label()}} {{form.code()}}</p>
    <p>{{form.submit(class="button_primary")}}</p>
  </div>
</form>

{% endblock %}

app/department/templates/list_department.html
{% extends "index.html" %}

{% block title %} Department List {% endblock %}

{% block content %}

<br>
<div class="table">
    <a class="button_primary" href="{{url_for('department.add_department')}}">Add Department</a>
    <span style="margin-right: 20px;"></span> 
    <form style="display: inline;" methods="POST" action="{{url_for('department.delete_all_department')}}"> 
        <button type="submit" onclick="return confirm('You sure you want to delete all departments')" class="button_danger">Delete all Departments</button>
    </form>
</div>

</br>

<table class="table">
    <tr>
        <th>S/N</th>
        <th>Department</th>
        <th>Department Name</th>
        <th>Department Code</th>
        <th>Action</th>
    </tr>

    {% for i in dep %}

    <tr>
        <th>{{ i.id }}</th>
        <th>{{ i.faculty.name }}</th>
        <th>{{ i.name }}</th>
        <th>{{ i.code }}</th>
        <td>
            <a class="button_primary" href="{{url_for('department.update_department', id=i.id)}}">Edit</a>&nbsp
            <form style="display: inline;" method="POST" action="{{url_for('department.delete_department', id=i.id)}}">
                <button type="submit" onclick="return confirm('You sure you want delete to this row')" class="button_danger">Delete</button>
            </form>
        </td> 
    </tr>
    {% endfor %}

</table>

{% endblock %}