app/group/models.py
from app import db


class group(db.Model):
    __tablename__='group'
    id=db.Column(db.Integer, primary_key=True)
    name=db.Column(db.String(50), nullable=False, unique=True)
    code=db.Column(db.String(10), nullable=False, unique=True)

    def __repr__(self):
        return f'<group>{self.name}'

app/group/forms.py
from flask_wtf import *
from wtforms import *
from wtforms.validators import *

class groupform(FlaskForm):
    id=HiddenField('id')
    group_name=StringField('group Name:', validators=[DataRequired()])
    group_code=StringField('group Code:', validators=[DataRequired()])
    submit=SubmitField('Save Changes')

app/group/__init__.py
from flask import Blueprint


group_bp=Blueprint('group',__name__, template_folder="templates", static_folder= 'statics')

from app.group import views

app/group/views.py
from flask import *

from app.group import group_bp
from app.group.forms import groupform
@group_bp.route("/group_list")

def get_group_list():
    return render_template("list_group.html")


#Get--retrieves information and passes the information to the html page
#POST-- to submit the data
#put
#delete-- to remove/delete


@group_bp.route('/add_group', methods=['GET', 'POST'])
def add_group():
    form=groupform()
    if form.validate_on_submit():
        group_name=form.group_name.data
        group_code=form.group_code.data
        #insert the record
        return redirect(url_for('group.get_group_list'))
    return render_template('add_group.html', form=form)

    

app/group/templates/add_group.html
{% extends 'index.html' %}

{% block title %} Add group {% endblock %}

{% block content %}
<form method="POST">
    <p>
        {{form.hidden_tag()}} <!--hemps protect against the cross site request forgery-->
    </p>
    <p>{{form.group_name.label()}}  <!--This is the text label-->
        {{form.group_name()}} <!--This is the text field-->
    </p>
    <p>{{form.group_code.label()}}  <!--This is the text label-->
        {{form.group_code()}} <!--This is the text field-->
    </p>
    <p>{{form.submit(class='.button_primary')}}  
    </p>
</form>
  

{% endblock %}

app/group/templates/list_group.html
{% extends "index.html" %}

{% block title %} Group List {% endblock %}

{% block content %}

<br>
<div class="table">
    <a class="button_primary" href="{{url_for('group.add_group')}}">Add Group</a> &nbsp;
    <hr>
            <form>
                <button type="submit" onclick="return confirm('Are you sure you want to delete all groups?')" class="button_danger">Delete all groups</button>
            </form>
</div>
<br>
<table class="table">
    <tr>
        <th>S/N</th>
        <th>group ID</th>
        <th>Group Name</th>
        <th>Course Name</th>
        <th>Course Code</th>
        <th>Action</th>
    
    </tr>

    <tr>
        <td>1</td>
        <td>1</td>
        <td>Computing</td>
        <td>Software Engineering</td>
        <td>SEN </td>
        <td><a class="button_primary" href="#">Edit</a> &nbsp
            <form>
                <button type="submit" onclick="return confirm('Are you sure you want to delete this row?')" class="button_danger">Delete</button>
            </form>
        </td>
    </tr>
</table>


{% endblock %} 