app/program/models.py
from app import db

class Program(db.Model):
    __tablename__= 'program'
    id = db.Column(db.Integer, primary_key = True)
    department_id = db.Column(db.Integer, db.ForeignKey('department.id'), nullable = False)
    name = db.Column(db.String(50), nullable = False, unique = True)
    code = db.Column(db.String(10), nullable = False, unique = True)

    department = db.relationship("Department", backref="program")

    def __repr__(self):
        return f'<Program>{self.name}'

app/program/forms.py
from flask_wtf import *
from wtforms import *
from wtforms.validators import *
from app.department.models import Department

class ProgramForm(FlaskForm):
    id = HiddenField("id")
    department_id=SelectField("Select dEPARTMENT")
    name=StringField("Program Name: ", validators=[data_required()])
    code=StringField("Program Code: ", validators=[data_required()])
    submit=SubmitField("Save Changes")

    def __init__(self, *args, **kwargs):
        super(ProgramForm, self).__init__(*args, **kwargs)
        self.department_id.choices=[(department.id, department.name) for department in Department.query.all()]

    

app/program/__init__.py
from flask import Blueprint


program_bp=Blueprint('program',__name__, template_folder="templates", static_folder= 'statics')

from app.program import views

app/program/views.py
from flask import *
from app.program import program_bp
from app.program.models import Program
from app.program.forms import ProgramForm
from app import db

@program_bp.route("/program_list", methods=["GET"])
def get_program_list():
    program = Program.query.all()
    return render_template("list_program.html", prog=program)


@program_bp.route("/add_program", methods=["GET", "POST"])
def add_program():
    forms=ProgramForm()
    if forms.validate_on_submit():
        department_id = forms.department_id.data
        program_name= forms.name.data
        program_code = forms.code.data

        new_program = Program(department_id=department_id, name=program_name, code = program_code)
        db.session.add(new_program)
        db.session.commit()
        return redirect(url_for("program.get_program_list"))

    return render_template("add_program.html", form=forms)



@program_bp.route('/delete_program/<int:id>', methods=['POST'])
def delete_program(id):
    program=Program.query.get_or_404(id)
    db.session.delete(program)
    db.session.commit()
    return redirect(url_for('program.get_program_list'))


@program_bp.route("/update_program/<int:id>", methods=["GET", "POST"])
def update_program(id):
    program=Program.query.get_or_404(id)
    form=ProgramForm(obj=program)
    if form.validate_on_submit():
        form.populate_obj(program)
        db.session.commit()
        return redirect(url_for("program.get_program_list"))
    
    return render_template("add_program.html", form=form)

@program_bp.route('/delete_all_program/', methods=['POST'])
def delete_all_program():
    Program.query.delete()
    db.session.commit()
    return redirect(url_for('program.get_program_list'))

app/program/templates/add_program.html
{% extends 'index.html' %} {% block title %} Add Program {% endblock %} {% block
content %}

<form method="POST">
  <p>{{form.hidden_tag()}}</p>

  <p>{{form.department_id.label()}} {{form.department_id()}}</p>

  <p>{{form.name.label()}} {{form.name()}}</p>
  <p>{{form.code.label()}} {{form.code()}}</p>
  <p>{{form.submit(class="button_primary")}}</p>
</form>

{% endblock %}

app/program/templates/list_program.html
{% extends "index.html" %}

{% block title %} Program List {% endblock %}

{% block content %}

<br>
<div class="table">
    <a class="button_primary" href="{{url_for('program.add_program')}}">Add Program</a>
    <span style="margin-right: 20px;"></span> 
    <form style="display: inline;" methods="POST" action="{{url_for('program.delete_all_program')}}"> 
        <button type="submit" onclick="return confirm('You sure you wan delete all the Program')" class="button_danger">Delete all Programs</button>
    </form>
</div>

</br>

<table class="table">
    <tr>
        <th>S/N</th>
        <th>program ID</th>
        <th>program Name</th>
        <th>Program Name</th>
        <th>Program Code</th>
        <th>Action</th>
    </tr>

    {% for i in prog %}

    <tr>
        <th>{{ i.id }}</th>
        <th>{{ i.department.id }}</th>
        <th>{{ i.department.name }}</th>
        <th>{{ i.name }}</th>
        <th>{{ i.code }}</th>
        <td>
            <a class="button_primary" href="{{url_for('program.update_program', id=i.id)}}">Edit</a>&nbsp
            <form style="display: inline;" method="POST" action="{{url_for('program.delete_program', id=i.id)}}">
                <button type="submit" onclick="return confirm('You sure you wan delete this stuff')" class="button_danger">Delete</button>
            </form>
        </td> 
    </tr>
    {% endfor %}

</table>

{% endblock %}